'use strict';


const PIECE_TYPES = {
  BLACK: 'BLACK',
  BLANK: 'BLANK',
  WHITE: 'WHITE',
};

const PIECE_TYPE_SYMBOL_TEXTS = {
  [PIECE_TYPES.BLACK]: 'x',
  [PIECE_TYPES.BLANK]: '-',
  [PIECE_TYPES.WHITE]: 'o',
};

const PRESET_RULE_TYPES = {
  NOT_USE: 'NOT_USE',
  STANDARD: 'STANDARD',
};


module.exports = {
  PIECE_TYPES,
  PIECE_TYPE_SYMBOL_TEXTS,
  PRESET_RULE_TYPES,
};
